version: "3.9"

services:
  # 1. Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 2. Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"

  # 3. Redis
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  # 4. FastAPI App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - redis
    ports:
      - "8000:8000"
    # environment: 
    #   - ENV_VAR=production  # example if you have environment variables

  # 5. Dummy Stock Server
  dummy_stock_server:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    ports:
      - "6789:6789"

  # 6. Streamlit Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    depends_on:
      - app
      - redis
    ports:
      - "8501:8501"
