FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY dummy_stock_server.py .

EXPOSE 6789

CMD ["python", "dummy_stock_server.py"]
